default:
    RUST_LOG=DEBUG cargo run
get FILENAME:
    cargo build --release && ./target/release/djinn_client_cli --host 127.0.0.1 --port 7777 get -f {{FILENAME}} -d .
put FILENAME:
    cargo build --release && RUST_LOG=DEBUG ./target/release/djinn_client_cli --host 127.0.0.1 --port 7777 put -f {{FILENAME}} -d .
sync:
    cargo build --release && RUST_LOG=DEBUG ./target/release/djinn_client_cli --host 127.0.0.1 --port 7777 sync
echo:
    cargo build --release && RUST_LOG=DEBUG ./target/release/djinn_client_cli --host 127.0.0.1 --port 7777 echo
lint:
    cargo clippy --fix
test:
    cargo test